[package]
name = "retrofit_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.14"
syn = {version="1.0.85", features=["full"]}
proc-macro2 = "1.0.36"